export const MONTHLY_SALES_REQUEST = 'MONTHLY_SALES_REQUEST'
export const MONTHLY_SALES_SUCCESS = 'MONTHLY_SALES_SUCCESS'
export const MONTHLY_SALES_FAIL = 'MONTHLY_SALES_FAIL'

export const PRODUCT_COUNT_REQUEST = 'PRODUCT_COUNT_REQUEST'
export const PRODUCT_COUNT_SUCCESS = 'PRODUCT_COUNT_SUCCESS'
export const PRODUCT_COUNT_FAIL = 'PRODUCT_COUNT_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'