export const CREATE_ORDER_REQUESTS = "CREATE_ORDER_REQUESTS";
export const CREATE_ORDER_SUCCESSS = "CREATE_ORDER_SUCCESSS";
export const CREATE_ORDER_FAILS = "CREATE_ORDER_FAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MY_ORDERS_REQUESTS = "MY_ORDERS_REQUESTS";
export const MY_ORDERS_SUCCESSS = "MY_ORDERS_SUCCESSS";
export const MY_ORDERS_FAILS = "MY_ORDERS_FAILS";

export const ORDER_DETAILS_REQUESTS = "ORDER_DETAILS_REQUESTS";
export const ORDER_DETAILS_SUCCESSS = "ORDER_DETAILS_SUCCESSS";
export const ORDER_DETAILS_FAILS = "ORDER_DETAILS_FAILS";

export const ALL_ORDERS_REQUESTS = "ALL_ORDERS_REQUESTS";
export const ALL_ORDERS_SUCCESSS = "ALL_ORDERS_SUCCESSS";
export const ALL_ORDERS_FAILS = "ALL_ORDERS_FAILS";

export const UPDATE_ORDER_REQUESTS = "UPDATE_ORDER_REQUESTS";
export const UPDATE_ORDER_SUCCESSS = "UPDATE_ORDER_SUCCESSS";
export const UPDATE_ORDER_RESETS = "UPDATE_ORDER_RESETS";
export const UPDATE_ORDER_FAILSS = "UPDATE_ORDER_FAILSS";

export const DELETE_ORDER_REQUESTS = "DELETE_ORDER_REQUESTS";
export const DELETE_ORDER_SUCCESSS = "DELETE_ORDER_SUCCESSS";
export const DELETE_ORDER_RESETS = "DELETE_ORDER_RESETS";
export const DELETE_ORDER_FAILSS = "DELETE_ORDER_FAILSS";